---

- name: "Add key to hosts authorized_keys"
  authorized_key:
    user=pandora
    key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
    state=present

- name: "Set Swap space to 1024MB"
  sudo: yes
  lineinfile:
    dest=/etc/dphys-swapfile
    regexp="CONF_SWAPSIZE\=100"
    line="CONF_SWAPSIZE=1024"
    state=present

- name: "Copy switch_halt script to /usr/local/bin"
  sudo: yes
  copy:
    src=switch_halt
    dest=/usr/local/bin
    mode="a+rwx"

- name: "Add switch_halt call in rc.local"
  sudo: yes
  lineinfile:
    dest=/etc/rc.local
    insertbefore="exit 0"
    line=switch_halt
    state=present


- name: 'Copy .bashrc'
  copy:
    src=.bashrc
    dest=/home/{{ user }}
    owner={{ user }}

- name: 'Copy .bash_aliases'
  copy:
    src=.bash_aliases
    dest=/home/{{ user }}
    owner={{ user }}

- name: 'Install vim'
  sudo: yes
  apt:
    name=vim
    update_cache=yes

- name: 'Install exuberant-ctags'
  apt:
    name=exuberant-ctags
    update_cache=yes

- name: 'Create vim home folder'
  file:
    path=/home/{{ user }}/.vim
    state=directory
    owner={{ user }}

- name: 'Create link to .vimrc'
  sudo: yes
  raw: ln -fs /home/{{ user }}/.vim/.vimrc /etc/vim/vimrc

- name: 'Copy vimrc'
  copy:
    src=.vimrc
    dest=/home/{{ user }}/.vim/.vimrc
    owner={{ user }}

- name: 'Git clone vundle plugin'
  git:
    repo=https://github.com/VundleVim/Vundle.vim.git
    dest=/home/{{ user }}/.vim/bundle/Vundle.vim
    accept_hostkey=yes
    key_file="/home/{{ user }}/.ssh/id_rsa.pub"

- name: 'Change ownership of vim directory'
  file:
    path=/home/{{ user }}/.vim
    state=directory
    owner={{ user }}
    recurse=yes

- name: 'Install vim plugins via vundle'
  sudo: no
  raw: vim -E -s -c "source ~/.vim/.vimrc" +PluginInstall +qall
  ignore_errors: yes

- name: 'Update'
  sudo: yes
  action: apt update_cache=yes

- name: 'Upgrade'
  sudo: yes
  action: apt upgrade=safe

